### ISSUE TITLE
TA comment: 使用者需求以及需求規格書

### ISSUE THREAD

**Issue by jo-ym** [OUOOOOOO/BaseProject-Cpp#1]
1. 使用者介面算是非功能性需求，此作業需要做功能性需求（-10）

*若有修改，請在此issue下回覆，否則不予修改及加分。

**Comment by OUOOOOOO** [comment]
已更新程式規格書和開發同意書。
(已得到客戶同意，將「使用者介面」更改為「登入系統」。)

[尊重。友善。包容_程式規格書.docx](https://github.com/OUOOOOOO/BaseProject-Cpp/files/2705261/_.docx)

[尊重。友善。包容_當個好學生努力上進_系統開發同意書.pdf](https://github.com/OUOOOOOO/BaseProject-Cpp/files/2705260/_._.pdf)

**Comment by jo-ym** [comment]
> 已更新程式規格書和開發同意書。
> (已得到客戶同意，將「使用者介面」更改為「登入系統」。)
> 
> [尊重。友善。包容_程式規格書.docx](https://github.com/OUOOOOOO/BaseProject-Cpp/files/2705261/_.docx)
> 
> [尊重。友善。包容_當個好學生努力上進_系統開發同意書.pdf](https://github.com/OUOOOOOO/BaseProject-Cpp/files/2705260/_._.pdf)

已修改分數
